### PR TITLE
Alignment and Footer Redesign 

### PR DESCRIPTION
**Pull request by AbhinavReddy-Dev**
# Description

This PR is for the issue #124 , along with some footer style upgrade for small and medium screens.
Changes have been made to the hamburger menu padding-top, alignment of items in second section of landing div. 
Sizes of illustrations are updated so as to maintain the same ratio across all screens.

Fixes # (issue)
#124  
Styling fixtures for Home page content and assets.

## Type of change
Styling changes

Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
 This is a PR for CSS, hence only UI testing has been done for different screens.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

Images for  reference

**Before**
Screenshot 2020-10-01 at 16 30 17

**After**
Screenshot 2020-10-01 at 16 30 52

**Before**
Screenshot 2020-10-01 at 16 31 34

**After**
Screenshot 2020-10-01 at 16 32 00

**Before**
Screenshot 2020-10-01 at 16 32 35
Screenshot 2020-10-01 at 16 33 08

**After**
Screenshot 2020-10-01 at 16 33 39
Screenshot 2020-10-01 at 16 33 55

### CODE REVIEW

**Review by imabp — APPROVED** [review]

**Comment by imabp** [comment]
Great work @AbhinavReddy-Dev

**Comment by AbhinavReddy-Dev** [comment]
@imabp Thank you, Let me know if there are any other styling issues, I can help others make a PR too if the changes are legit. 😁

**Comment by imabp** [comment]
@AbhinavReddy-Dev For now you can create issues or any feature request on the website. 
Also try to see other repositories, like KLADI, AirJSON which are bit advanced and needs serious contribution.

**Comment by AbhinavReddy-Dev** [comment]
@imabp Sure, I’ll give it a look!

**Pull request merged**
