### PR TITLE
Add Team Page

### PR DESCRIPTION
**Pull request by pixan198**
Tech Phantom Team Page
 I've implemented the template
#12 #3 
@Souvikns @imabp @JoshuaPoddoku

### CODE REVIEW

**Review by imabp — APPROVED** [review]
Great work @pixan198 . I saw you have used React components. 
@Souvikns, @imabp  will  make it bit modular and functional components

**Comment by pixan198** [comment]
@imabp 
Yeah, I'm not comfortable with functional components so used it

**Comment by puranjay123** [comment]
Group 2
Event page review @imabp

**Comment by puranjay123** [comment]
Group 3
Event page review/// @imabp  @JoshuaPoddoku

**Comment by JoshuaPoddoku** [comment]
Great work. I liked the arrangement based on hierarchy! Just improve this design matching with the team page UI. (Simple and minimal)

**Comment by puranjay123** [comment]
yes  i am currently changing it to our team page UI.

**Comment by imabp** [comment]
@puranjay123 , we are having simple cards design  for event holders. So event page, would be having those cards. You may come up with the designs having cards . 
For example of card: https://techphantoms.netlify.app/events

**Pull request merged**
