### PR TITLE
feature-project-structure-documentation

### LINKED ISSUE #114: We need documentation for Project Structure
Project Directory will help beginners to understand the code.
Project Structure must be saved in root location with name `projectStructure.md`
This structure must describe each and every folders or file and their role in the project.

### PR DESCRIPTION
**Pull request by TomerPacific**
# Description

Added further description of project structure

Fixes #114 

## Type of change

Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

No testing required

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by imabp** [comment]
Great. You are going right!

**Comment by TomerPacific** [comment]
@imabp - what else would you like described? As I have covered all the main directories. Is it necessary to describe every component or every asset?

**Comment by imabp** [comment]
Thats all fine. We do need to maintain some abstraction levels. So no need to describe each and every asset

**Comment by imabp** [comment]
@TomerPacific shall I merge it or are you still working on it ?

**Comment by imabp** [comment]
We are merging this now, because we got some comments regarding codebase understanding. 
Send us a new PR, if you modify any changes to it 

Thankyou @TomerPacific . Its great to have you contributing here.

**Pull request merged**
