### PR TITLE
Souvik

### PR DESCRIPTION
**Pull request by Souvikns**

### CODE REVIEW

**Comment by Souvikns** [comment]
@imabp we need to change a lot of things

**Comment by imabp** [comment]
@Souvikns Updated

**Review by imabp — APPROVED** [review]

**Comment by imabp** [comment]
Build Fail
I think some variables are not defined

**Comment by Souvikns** [comment]
just accept my changes for fixing the conflict. 
I have connected the data layer, still, the time is coming in string. 
also, I don't think we should have a recording link as this is for people to know about our events and we won't have the recording until the event occurs.

**Pull request merged**
