### PR TITLE
decrease padding from the hero section

### PR DESCRIPTION
**Pull request by rishipurwar1**
Decrease padding from the hero section of the homepage #105

### CODE REVIEW

**Comment by imabp** [comment]
Nice work @rishipurwar1 . We will merge it on or after 1st October

**Comment by rishipurwar1** [comment]
I think hackoctober is already started.  1 October is already there is some countries

**Comment by imabp** [comment]
Sorry my bad. 
Its started.
Thanks for the info @rishipurwar1

**Comment by rishipurwar1** [comment]
No problem☺
Keep Contributing...

**Pull request merged**
