### PR TITLE
add 404 error page

### LINKED ISSUE #107: Design 404 page
Till now, we don't have a  Error 404 Page yet. 
So this is call for UI designers to prepare a  creative design based on current theme for 404  page

PS: This is hacktoberfest labelled. Will be merged on or after 1st October

### PR DESCRIPTION
**Pull request by ampsteric**
# Description

The 404 Error Page has been added.
I have created a new Component(ErrorPage) in the Components folder.
please review and accept the PR.

# Fixes 
#107 has been resolved

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Souvikns** [comment]
Ok, so there is a conflict. I would suggest that you update your branch with the development branch.

**Review by Souvikns — APPROVED** [review]

**Comment by imabp** [comment]
We dont see any component Error 404 in your commit

**Comment by ampsteric** [comment]
Please let me push my changes directly to the master branch.'
it would be much better as I have already spent much time making this page.

**Comment by imabp** [comment]
@ampsteric please make a new PR. We are not able to see your Error Component code.

No one is denying..Just make a new PR again.

**Comment by ampsteric** [comment]
Okay.
I have made a new PR #139 with ErrorPage component in it.

kindly review and accept my PR.

**Pull request closed without merging**
