### PR TITLE
Added Dark Theme to the landing page

### PR DESCRIPTION
**Pull request by DeadSpoon18**

### CODE REVIEW

**Comment by DeadSpoon18** [comment]
why all checks failed??

**Comment by Souvikns** [comment]
@DeadSpoon18 try to check for warning or errors that you are having in your code.

**Comment by Souvikns** [comment]
@DeadSpoon18 good job. Can you attach a **screenshot** of the web page.

**Comment by Souvikns** [comment]
@DeadSpoon18 no need I just saw the deploy preview and it is looking good. I am merging this pr.

**Comment by DeadSpoon18** [comment]
:smiley:

**Pull request merged**
