### PR TITLE
Overflow in projects section in smaller devices (Solved) issue #155

### PR DESCRIPTION
**Pull request by Harshchourasiya**
# Description

I change the width of box to set it with smaller devices

Fixes # (issue)

#115 

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

**Before**

IssusSecond

**After**

IssueSecondSolved

### CODE REVIEW

**Comment by imabp** [comment]
@Harshchourasiya If you remove the left margin , and make everything centred. 
I think that would look bit cool.

**Comment by Harshchourasiya** [comment]
Yes, I will.

**Comment by Harshchourasiya** [comment]
> @Harshchourasiya If you remove the left margin , and make everything centred.
> I think that would look bit cool.

Yes, I will do that

**Comment by Harshchourasiya** [comment]
> @Harshchourasiya If you remove the left margin , and make everything centred.
> I think that would look bit cool.

Hey, Where can i change code. can i generate another pull request

**Comment by imabp** [comment]
You can change the code at your fork. And when you pull request, it will be counted in this PR only

`src/pages/projects.jsx`

Has the modular implementation.

**Comment by Harshchourasiya** [comment]
> You can change the code at your fork. And when you pull request, it will be counted in this PR only
> 
> `src/pages/projects.jsx`
> 
> Has the modular implementation.

This pull request also count in hacktoberfest bro

**Comment by imabp** [comment]
If you wish, you can generate other pull requests too. But PRs will be
counted as hacktoberfest pull request and will be reviewed by our
maintainer @souvikns

**Comment by Harshchourasiya** [comment]
Hey, I Change code and commit it here 
Now, This is look like this 

**Now**


issuesSecondSolvedSecond




I think Now this is okay

**Review by imabp — APPROVED** [review]

**Comment by imabp** [comment]
Thankyou for making it mobile responsive. Merged to development

**Pull request merged**
