### PR TITLE
Errorpage

### PR DESCRIPTION
**Pull request by ampsteric**
# Description

The 404 Error Page has been added.
I have created a new Component(ErrorPage) in the Components folder.
please review and accept the PR.

Fixes # (issue)
#107 has been resolved

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by ampsteric** [comment]
were you able to find my work? @imabp

**Comment by imabp** [comment]
@ampsteric I cannot see your commits.
Only the commits for error page are done by @elitechef 
image

**Comment by ampsteric** [comment]
yes actually I have 2 accounts enabled in the same machine. all the work committed by @elitechef are actually comitted by me.
I also apologize for the same but I am unable to remove my 2nd account from my terminal.
Did you find the ErrorPage component?
Does it works fine?

**Comment by imabp** [comment]
Issue has been resolved @ampsteric 

Suggestions:
You need to work on the code quality.
Bit need to do research on how React Router handles Error 404 requests.

**Pull request closed without merging**
