### PR TITLE
Custom_scroll_bar #72

### LINKED ISSUE #72: Custom Scroll bar for the website
## Requirement:
To have a custom scrollbar design which suits the background and plus makes website look more aesthetic

image

### PR DESCRIPTION
**Pull request by sejalshri**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change

Fixes #72 

Added Jquery scroll() method
added some CSS styling required for custom scroll bar.

Please delete options that are not relevant.

-  [ ] Bug fix (non-breaking change which fixes an issue)
-  [x] New feature (non-breaking change which adds functionality)
-  [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-  [ ] This change requires a documentation update

# How Has This Been Tested?
tested by running on my own system on various browsers. It seems to be working fine.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sejalshri** [comment]
@imabp @JoshuaPoddoku kindly review this PR.

**Comment by imabp** [comment]
@sejalshri 
You have put up efforts and we admire it. But there are some issues with it.
###  We cant  make our site slow for slower networks.
Considering this, we dont want to go with JQuery or any other library.

### How to do then ?
Step 1:  Write a custom javascript with appending a div for the scrollbar
Step 2: Add Event Handlers to know when the user scrolls.

## We are waiting for the updated PR to `development branch`

**Comment by imabp** [comment]
See @sejalshri  you will learn more about how DOM works while solving this issue. 
Give your best.

**Comment by sejalshri** [comment]
okay , i'll work on it.

**Pull request closed without merging**
