### PR TITLE
converted projects holder from chakra to material-ui

### LINKED ISSUE #164: 📌We are migrating to Material UI
#  📌We will be  migrating to Material UI 
Slowly slowly every component will be converted to Material UI ones. 

Anyone who would like to take part in this process, please comment down on this issue.

I think we should break this process as much as possible, due to the sheer number of components currently present. 

## TODO
- #### Landing Page
- [x] Appbar
- [x] Drawer - @Souvikns 
- [x] Footer - @senshiii
- [x] landing page layout - @imabp 
- #### Project Page
- [x] Project card - @Souvikns 
- [x] Project page layout - @Souvikns 
- #### Team Page
- [ ] Team Profile Card - @sandy9808 
- [ ] Team Page layout
- #### Event Page - @Souvikns 
- [x] Event card 
- [ ] Event Layout 
- #### 404 Page
- [x] 404 page layout - @sandy9808 

---
> Comment to pick components.
---

### PR DESCRIPTION
**Pull request by Souvikns**
# Description
Converted from chakra-UI to Material-UI. 

Fixes #164

### CODE REVIEW

**Comment by imabp** [comment]
Not Mobile responsive yet.

image

**Comment by Souvikns** [comment]
Check the layout for the mobile I guess now it is fixed.

**Comment by imabp** [comment]
@Souvikns I think the UI is breaking at mobile point.. little bit still.

image

**Comment by Souvikns** [comment]
I don't know which link you are watching but, check this [link](https://deploy-preview-168--techphantoms.netlify.app/)

image

**Comment by imabp** [comment]
I always test first for iPhone 5 . Because that is only the second smallest screen mobile after samsung fold

**Comment by Souvikns** [comment]
Fixed it

**Comment by imabp** [comment]
Great work! @Souvikns

**Pull request merged**
