### PR TITLE
landing section made

### PR DESCRIPTION
**Pull request by hkaur008**
found assests of top section only
preview links in route

### CODE REVIEW

**Comment by imabp** [comment]
@hkaur008  Build has failed due to some syntax error on line

screencapture-app-netlify-sites-techphantoms-deploys-5f533c663d25d40007445316-2020-09-05-12_53_58

**Comment by imabp** [comment]
@hkaur008 please see the build log

**Comment by hkaur008** [comment]
ohk i check

**Comment by imabp** [comment]
Builds Failed (App Crash) I think some naming issue 👇
image

**Comment by hkaur008** [comment]
just made some changes again

**Comment by imabp** [comment]
@hkaur008  pls dont close the pull request. Until the build gets success. Build failed again
screencapture-app-netlify-sites-techphantoms-deploys-5f533c663d25d40007445316-2020-09-05-12_53_58

**Comment by imabp** [comment]
@hkaur008 I am removing duplicate props in codebase. Pull request after that

**Comment by imabp** [comment]
Pull changes now @hkaur008 and the pull request.

**Comment by imabp** [comment]
@hkaur008  please sync your local repository, using `git pull` and resolve the merge conflict, by accepting incoming changes.

**Comment by hkaur008** [comment]
ohk

**Comment by imabp** [comment]
@hkaur008 , on your deploy, I couldnt see changes. please recheck on local host and then send pull request. 😊😊

**Comment by Souvikns** [comment]
All checks have passed @hkaur008 can you please attach the screenshot of the UI that you have built

**Comment by hkaur008** [comment]
image

**Comment by Souvikns** [comment]
@hkaur008 all the design is fine, just remove the background-color and try to see if you could make the tech phantoms logo a bit small. I will merge your pull request after these changes.

**Comment by hkaur008** [comment]
light mode or dark mode background  has to be removed, logo small in smaller sizes or full sizes?

**Comment by Souvikns** [comment]
in light and dark mode the color will come from the theme so you don't need to build light and dark mode separately. the background color that I am talking about it that grey bg, remove that. The logo is alright, I will change it after merging.

**Comment by hkaur008** [comment]
> in light and dark mode the color will come from the theme so you don't need to build light and dark mode separately. the background color that I am talking about it that grey bg, remove that. The logo is alright, I will change it after merging.

blue one?

**Comment by Souvikns** [comment]
remove the grey background form the light component and delete the dark component completely.

**Comment by Souvikns** [comment]
I guess you created new routes for testing your UI also do remove those routes and import your component in `pages/index.jsx`

**Comment by Souvikns** [comment]
@hkaur008 all checks have passed, good job, I am merging your pr

**Pull request merged**
